### PR TITLE
Prepare dialyzer temp dir and add gitignore

### PR DESCRIPTION
**Pull request by webdeb**
After dialyzer has been run, you have to manually add the generated dir to your gitignore, we can make it automatically?

### CODE REVIEW

**Comment by JakeBecker** [comment]
That's clever!

If we're going to do that, though, we should probably put the gitignore file in the `.elixir_ls` directory. Other tempfiles are stored there too, such as Dialyzer's manifest and temporary beam files written by the debugger.

I'm a little unsure if this is warranted at all, though. It's pretty common for IDEs to write their metadata files to a hidden folder (`.idea` in IntelliJ, for example). The usual advice given is that users should add these folders to their global, system-wide `.gitignore` files.

Are you aware of any other IDEs or IDE plugins using this approach? I'm not necessarily opposed, but I'd feel more comfortable merging this if there's an example of other IDE plugins doing it too.

**Comment by shritesh** [comment]
Considering that the `_build` directory is where compiled artifacts are stored and it is included in the default .gitignore generated by `mix` already, would it be better to move `.elixir_ls` to that directory instead?

**Comment by webdeb** [comment]
Hello @JakeBecker, I am really sorry for the late response.

I think, that `.idea / .vscode` files are a bit of an other concern, when added to git they can help to provide useful configurations for teams.

However, I've updated the code as recommended, and btw. I really like how the extension performs now. Thanks for your work on this, and again sorry, that I missed to reply earlier :)

**Comment by JakeBecker** [comment]
Going through old PRs. I think the right approach here is to just add .elixir_ls to your global gitignore. Gonna close this. Thanks!

**Pull request closed without merging**
