### PR TITLE
Add LICENSE file for project

### LINKED ISSUE #119: What's the license?
Or, on the off chance I've become spectacularly (albeit selectively) blind: Can you document the license more clearly?

### PR DESCRIPTION
**Pull request by balduncle**
@JakeBecker I am making the assumption that you are okay with Apache 2.0 but it seemed like a reasonable choice given that Elixir itself uses this license.  Thanks.

Closes #119.

### CODE REVIEW

**Comment by Shados** [comment]
IANAL, but I'm pretty sure you'd have to get the other 11 contributors to explicitly agree to the licensing, or replace their contributions.

**Comment by balduncle** [comment]
Good point. If we know what license we want to go with I’m willing to reach out to contributors to get their approval, assuming consent on a github issue is sufficient.

**Comment by JakeBecker** [comment]
Hey, sorry for being unresponsive here. You're right, choosing a license is overdue. I don't have a strong opinion on it, and Apache 2.0 seems fine to me.

I do want to get opinions from contributors in case anyone has a stronger opinion. Pinging all contributors who have contributed more than a 1-liner:

@mattbaker 
@lukaszsamson 
@GoNZooo
@percygrunwald

Any thoughts on MIT vs. Apache 2.0 vs. BSD license? If I don't hear any objections within a week or so, I'm going to take that as confirmation that Apache 2.0 is fine.

**Comment by GoNZooo** [comment]
I don't have a strong or particularly educated opinion on this and these are all of the weak copyleft kind, so I think they're probably all fine.

**Comment by percygrunwald** [comment]
Apache 2.0 is fine with me, thanks!

**Comment by mattbaker** [comment]
Apache 2.0 looks good to me.

**Comment by lukaszsamson** [comment]
It's fine with me also

**Pull request merged**
