### PR TITLE
Support Phoenix LiveView

### PR DESCRIPTION
**Pull request by leandrocp**
It's a WIP because need to write tests and add support for the new `~L` sigil

Reference: https://github.com/phoenixframework/phoenix_live_view/blob/9eb53ebf717003cd7edb17df09c26ccb8993c4d0/lib/phoenix_live_view.ex#L159

See: JakeBecker/vscode-elixir-ls#128

### CODE REVIEW

**Comment by leandrocp** [comment]
See https://github.com/JakeBecker/vscode-elixir-ls/pull/128

**Comment by leandrocp** [comment]
Still need to write tests and add support for the new `~L` sigil (https://github.com/phoenixframework/phoenix_live_view/blob/9eb53ebf717003cd7edb17df09c26ccb8993c4d0/lib/phoenix_live_view.ex#L159)

**Comment by OvermindDL1** [comment]
> and add support for the new ~L sigil

Shouldn't that be just like any other sigil?  Any library can define their sigils, and `~L` could easily come from another library, not just LiveView.

**Comment by leandrocp** [comment]
> > and add support for the new ~L sigil
> 
> Shouldn't that be just like any other sigil? Any library can define their sigils, and `~L` could easily come from another library, not just LiveView.

@OvermindDL1 it makes sense. Do you know if there's anything else that needs to be done in order to properly support LiveView ? And also, can you give me a hand in this https://github.com/JakeBecker/vscode-elixir-ls/pull/128#issuecomment-476217911 ?

**Comment by OvermindDL1** [comment]
I don't think anything special would need to be done for liveview other than just adding `.html.leex` to the list of extensions that vscode supports for an html editor with an embedded eex editor.

**Comment by markevich** [comment]
Hi @leandrocp  . Any chances that it will be merged?)

**Comment by leandrocp** [comment]
> Hi @leandrocp . Any chances that it will be merged?)

@markevich I just sent a commit to correctly recognize liveeex files: https://github.com/JakeBecker/vscode-elixir-ls/pull/128

But if you don't want to wait for the package to be published, you can build the package yourself:

```
git clone --recursive https://github.com/leandrocp/vscode-elixir-ls
cd vscode-elixir-ls
git checkout support-phoenix-live-view
cd elixir-ls
mix deps.get
mix elixir_ls.release
cd ..
npm install -g vsce
npm install
vsce package
```

A file `elixir-ls-0.2.24.vsix` will be generated in the current path. On vscode, go to Extensions > ... > Install from VSIX... to install the package.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

If you're still interested in merging this PR, please do the following:

1. Check that the issue you're addressing still occurs with the latest version of the VS Code plugin (which is published from the new repo)
2. If your PR references a Github issue, check if there's already an issue filed on the new repo and create one if not
3. Rebase your PR from the new repo (which has diverged significantly) and re-submit it there.

Thank you!

**Pull request closed without merging**
