### PR TITLE
Support complete on another editors- Add snippet support - Fix test

### PR DESCRIPTION
**Pull request by WolfDan**
Hey! I've been testing elixir-ls with Sublime Text 3 LSP, I didn't made it work at first time so I fork the project and did a few fixes to make it work on another editors, hope is well implemented ^^'

I've only tested on Sublime Text 3 in Windows OS, elixir 1.6.0-dev, Erlang 20.1

_I just found a little bug with the pipe operator that I didn't manage to solve, if you write a module or a function after `|>` the auto-complete don't work_

Greetings!

### CODE REVIEW

**Comment by JakeBecker** [comment]
This is cool!

I'm about to leave for vacation, so I'll review it fully in ~2 weeks once I'm back. Thanks for your work on this!

**Comment by WolfDan** [comment]
I pushed a few changes for the snippets, I also tested it on Visual Code and it fix the problem when you write a module and later `.` it don't give any completion

Don't forget delete the snippets on the VS Code repository since now it's showed as duplicated

**Comment by JakeBecker** [comment]
I merged the autocompletion trigger characters and the formatting change outside of this PR, since they're not directly related to the snippets.

Do you find these snippets useful?  To be honest, I'm tempted to get rid of them altogether. I copied them along with other client code from fr1zle/vscode-elixir, but I never actually use them myself, and they overlap with results from `Kernel.SpecialForms`. Going with those results has the advantage of showing documentation and being accurate for whichever Elixir version is in use, though the snippet text they insert is not always what you want.

In the latest v0.2.9 release of vscode-elixir-ls, I changed the default for autocomplete to only show up after typing a "." or if you trigger it manually, so these snippets are going to be less discoverable. Can you tell me which ones you tend to use? That might be helpful in deciding how to proceed.

**Comment by WolfDan** [comment]
I don't have any problem to get rid of them ^^ you can add them by writting plugins, _is just to support all editor in a universal way_ (For example sublime just need to add the language server path and you have all the features without need to write any plugin etc...) 

There is a problem with `Kernel.SpecialForms` that are recognized as functions so for example y write `case` it will autocomplete into `case(condition, clauses)` with snippets is better because it turn into 

```elixir
case do
    -> 

end
```

Same with `defmodule` and other snippets that in `Kernel.SpecialForms` shows arguments and parenthesis that you don't use and don't add the `do end` statements

**Comment by JakeBecker** [comment]
Closing this old PR. I've changed how snippets are handled, they're now done in the autocompletion provider, so if you want to suggest changes to them that's the place.

**Pull request closed without merging**
